package com.service.utils.ui

import androidx.compose.runtime.compositionLocalOf
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

data class Spacing(
    val minusTwoDp: Dp = (-2).dp,
    val minusFiveDp: Dp = (-5.5).dp,
    val zeroDp: Dp = 0.dp,
    val oneDp: Dp = 1.dp,
    val oneHalfDp: Dp = 1.5.dp,
    val twoDp: Dp = 2.dp,
    val threeDp: Dp = 3.dp,
    val fourDp: Dp = 4.dp,
    val fiveDp: Dp = 5.dp,
    val sixDp: Dp = 6.dp,
    val sevenDp: Dp = 7.dp,
    val eightDp: Dp = 8.dp,
    val nineDp: Dp = 9.dp,
    val tenDp: Dp = 10.dp,
    val elevenDp: Dp = 11.dp,
    val twelveDp: Dp = 12.dp,
    val fourteenDp: Dp = 14.dp,
    val fifteenDp: Dp = 15.dp,
    val sixteenDp: Dp = 16.dp,
    val seventeenDp: Dp = 17.dp,
    val eighteenDp: Dp = 18.dp,
    val nineteenDp: Dp = 19.dp,
    val twentyDp: Dp = 20.dp,
    val twentyOneDp: Dp = 21.dp,
    val twentyTwoDp: Dp = 22.dp,
    val twentyThreeDp: Dp = 23.dp,
    val twentyFourDp: Dp = 24.dp,
    val twentyFiveDp: Dp = 25.dp,
    val twentyEightDp: Dp = 28.dp,
    val thirtyDp: Dp = 30.dp,
    val thirtyTwoDp: Dp = 32.dp,
    val thirtyFiveDp: Dp = 35.dp,
    val thirtySixDp: Dp = 36.dp,
    val thirtySevenDp: Dp = 37.dp,
    val fortyDp: Dp = 40.dp,
    val fortyTwoDp: Dp = 42.dp,
    val fortySixDp: Dp = 46.dp,
    val fortyEightDp: Dp = 48.dp,
    val fiftyTwoDp: Dp = 52.dp,
    val fiftySixDp: Dp = 56.dp,
    val fiftyEightDp: Dp = 58.dp,
    val sixtyDp: Dp = 60.dp,
    val sixtyTreeDp: Dp = 63.dp,
    val sixtyFourDp: Dp = 64.dp,
    val sixtySixDp: Dp = 66.dp,
    val sixtyEightDp: Dp = 68.dp,
    val seventyTwoDp: Dp = 72.dp,
    val seventyFourDp: Dp = 74.dp,
    val eightyDp: Dp = 80.dp,
    val ninetyFiveDp: Dp = 95.dp,
    val hundredDp: Dp = 100.dp,
    val hundredThirtyDp: Dp = 130.dp,
    val hundredFiftyDp: Dp = 150.dp,
    val hundredSixtyDp: Dp = 160.dp,
    val hundredSevenDp: Dp = 170.dp,
    val hundredEightyDp: Dp = 180.dp,
    val twoHundredThirtyDp: Dp = 230.dp,
    val twoHundredFiftyDp: Dp = 250.dp,
    val twoHundredEightyDp: Dp = 280.dp,
    val threeHundredDp: Dp = 300.dp,
    val threeHundredThirtyDp: Dp = 350.dp,
    val threeHundredSixtyDp: Dp = 360.dp,
    val threeHundredEightyDp: Dp = 380.dp,
    val fourHundredThirtyDp: Dp = 430.dp,
    val sixHundredDp: Dp = 600.dp,
)

val LocalSpacing = compositionLocalOf { Spacing() }